"""Flask app for the web dashboard + Phase-2 operator control.

Reuses :mod:`tools.dashboard.state` — the decision-layer data model
is presentation-agnostic (pure Python, no UI dep). The TUI renders
via Rich markup; this app renders via Jinja templates. Both surface
the same panels (health, coverage, bottlenecks, freshness, learning,
diversity, next-action, counters).

Phase 2 adds a control layer — the dashboard is no longer read-only.
Operators trigger pipeline actions (Add Maps / Run Pipeline / Train
AI / Score / Generate-stub) via HTTP. The action catalogue + worker
lives in :mod:`tools.dashboard_web.actions`.

Routes:
  GET  /                          HTML dashboard + control panel
  GET  /api/state                 JSON snapshot
  GET  /healthz                   cheap liveness (no DB)
  GET  /api/actions               JSON action catalogue
  GET  /api/actions/status        JSON current + last-completed run
  POST /api/actions/<name>        kick off action <name>
  GET  /api/actions/<id>/log      Server-Sent Events stream of stdout

Auto-refresh of the state snapshot is HTML ``<meta http-equiv="refresh">``
— simplest correct answer at a 10-second cadence. Action logs stream
via SSE only while an action is in flight.

Deliberately simple:
- No auth. Bind to localhost by default; set DASHBOARD_HOST for LAN.
- Single-action-at-a-time lock. The 4 GB host can't parallelise heavy
  pipeline stages (see project_pipeline_memory_budget.md). Second
  action request while one is running returns HTTP 409.
- No persistent queue. A Flask restart kills in-flight actions; the
  operator re-triggers.
"""
from __future__ import annotations

import json
import logging
import os
import re
import sys
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from flask import (
    Flask,
    Response,
    abort,
    jsonify,
    render_template,
    request,
    send_from_directory,
    stream_with_context,
)

from tools.dashboard_web.actions import ACTIONS, ActionWorker, tail_stream

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_LOG = logging.getLogger(__name__)

# Where generate-map writes its artifacts. Matches the path template in
# tools.dashboard_web.actions._generate_map_args.
_GENERATED_MAPS_DIR = REPO_ROOT / "reports" / "generated-maps"

# Where `emit-gbx` writes the .Map.Gbx exports. Matches
# src.generation.gbx_writer.DEFAULT_GBX_OUTPUT_DIR.
_GENERATED_GBX_DIR = REPO_ROOT / "reports" / "generated-gbx"

# Cap how many artifacts the /api/generated-maps endpoint returns. Each
# summary is ~500 bytes so this is bounded; existing on-disk archives
# remain downloadable individually even when they drop off the list.
_GENERATED_LIST_CAP: int = 20

# Per-filename safety gates for the download endpoints. Filenames are
# generated by our own code (no user-supplied text enters the path),
# but the endpoints are public — strict whitelists cost nothing and
# eliminate path-traversal as a class even if that invariant slips.
_SAFE_FILENAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,199}\.json$")
_SAFE_GBX_FILENAME_RE = re.compile(
    r"^[A-Za-z0-9][A-Za-z0-9._-]{0,199}\.Map\.Gbx$"
)


def _fetch_state_sync() -> "DashboardState":
    """Gather a :class:`DashboardState` snapshot from the DB. Lazy-
    imports the project adapters so the Flask app imports cleanly
    even when the DB is unreachable — collection failure goes into
    the ``error`` field rather than raising."""
    try:
        sys.path.insert(0, str(REPO_ROOT))
        from src.storage.mariadb import open_connection
        from src.utils.config import load_config
        from tools.dashboard.state import DashboardState, fetch_state
    except Exception as exc:  # noqa: BLE001
        from tools.dashboard.state import DashboardState
        return DashboardState(
            collected_at=datetime.now(tz=timezone.utc),
            error=f"import failed: {exc}",
        )
    try:
        conn = open_connection(load_config(None))
    except Exception as exc:  # noqa: BLE001
        return DashboardState(
            collected_at=datetime.now(tz=timezone.utc),
            error=f"db connect failed: {exc}",
        )
    try:
        return fetch_state(conn)
    finally:
        conn.close()


def _humanize_age_filter(ts: datetime | None) -> str:
    """Jinja filter mirroring the TUI's age formatting."""
    from tools.dashboard.render import _humanize_age
    return _humanize_age(ts)


def _percent_filter(num: float | int, denom: float | int) -> str:
    if not denom:
        return "—"
    return f"{(num / denom) * 100:.0f}%"


def _state_to_dict(state: "DashboardState") -> dict[str, Any]:
    """Serialize a DashboardState for the JSON endpoint. ``asdict``
    unpacks the dataclasses; we coerce datetimes to ISO strings so
    the payload is JSON-native."""
    raw = asdict(state)
    # datetimes to ISO
    raw["collected_at"] = state.collected_at.isoformat()
    for entry in raw.get("freshness") or []:
        ts = entry.get("completed_at")
        if hasattr(ts, "isoformat"):
            entry["completed_at"] = ts.isoformat()
    return raw


def _serialize_catalogue() -> list[dict[str, Any]]:
    return [
        {
            "name": spec.name,
            "title": spec.title,
            "hint": spec.hint,
            "expected_minutes": spec.expected_minutes,
        }
        for spec in ACTIONS.values()
    ]


def _serialize_run(run: Any) -> dict[str, Any] | None:
    if run is None:
        return None
    return run.to_dict()


def _summarize_generated_artifact(path: Path) -> dict[str, Any] | None:
    """Read one generated-map JSON artifact and extract the fields the
    UI needs to render the result panel. Returns None if the file
    isn't parseable or doesn't look like a generation-v0 artifact —
    callers filter the list defensively rather than surfacing a
    half-understood row.

    Kept intentionally cheap (no schema validation here, just field
    plucks) — the listing endpoint pays this cost for every artifact
    each call and we don't cache.
    """
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError):
        return None
    # Accept the whole generation-v0.x family. New schema revs that
    # add fields on top of v0 should surface in the UI too; rejecting
    # them here silently hides Level-2 stripped artifacts (v0.1) etc.
    if not isinstance(data, dict):
        return None
    schema_version = data.get("schema_version") or ""
    if not schema_version.startswith("generation-v0"):
        return None
    inputs = data.get("inputs") or {}
    fin = data.get("finishability") or {}
    route = data.get("route") or {}
    route_intervals = route.get("intervals") or []
    map_block = data.get("map") or {}
    return {
        "filename": path.name,
        "size_bytes": path.stat().st_size,
        "mtime": datetime.fromtimestamp(
            path.stat().st_mtime, tz=timezone.utc,
        ).isoformat(),
        "schema_version": schema_version,
        "run_id": data.get("run_id"),
        "generated_at": data.get("generated_at"),
        "base_map_id": inputs.get("base_map_id"),
        "base_map_source_id": inputs.get("base_map_source_id"),
        "style_tag_filter": inputs.get("style_tag_filter"),
        "difficulty": inputs.get("difficulty"),
        "random_seed": inputs.get("random_seed"),
        "strip": inputs.get("strip", False),
        "route_verified": fin.get("route_verified"),
        "reject_reason": fin.get("reject_reason"),
        "estimated_time_ms": fin.get("estimated_time_ms"),
        "ai_confidence": fin.get("ai_confidence"),
        "interval_count": len(route_intervals),
        # Level-2 diagnostic. 0 for v0 artifacts; real counts for v0.1.
        "stripped": bool(map_block.get("stripped", False)),
        "kept_block_count": map_block.get("kept_block_count"),
        "base_block_count": map_block.get("base_block_count"),
    }


def _list_generated_artifacts(
    root: Path | None = None,
    *,
    limit: int = _GENERATED_LIST_CAP,
) -> list[dict[str, Any]]:
    """List recent generated-map artifacts as summary dicts, most
    recent first, capped at ``limit``.

    ``root`` defaults to the module-level ``_GENERATED_MAPS_DIR`` at
    call time (not import time) so tests can monkeypatch the dir
    without re-importing.
    """
    if root is None:
        root = _GENERATED_MAPS_DIR
    if not root.exists():
        return []
    paths = sorted(
        (p for p in root.glob("*.json") if p.is_file()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    out: list[dict[str, Any]] = []
    for p in paths:
        summary = _summarize_generated_artifact(p)
        if summary is not None:
            out.append(summary)
            if len(out) >= limit:
                break
    return out


def _find_run(worker: ActionWorker, run_id: str) -> Any:
    cur = worker.current
    if cur is not None and cur.id == run_id:
        return cur
    last = worker.last_completed
    if last is not None and last.id == run_id:
        return last
    return None


def create_app(
    *,
    state_fetcher: Any = None,
    refresh_seconds: int = 10,
    worker: ActionWorker | None = None,
) -> Flask:
    """Construct a Flask app. ``state_fetcher`` is an override point
    for tests so they can inject a stub without hitting the DB.
    ``refresh_seconds`` tunes the HTML meta-refresh cadence.
    ``worker`` is a dependency-injection point for tests to supply a
    stubbed :class:`ActionWorker`."""
    app = Flask(
        __name__,
        template_folder=str(Path(__file__).parent / "templates"),
        static_folder=str(Path(__file__).parent / "static"),
    )
    fetch = state_fetcher or _fetch_state_sync
    action_worker = worker or ActionWorker()
    app.jinja_env.filters["humanize_age"] = _humanize_age_filter
    app.jinja_env.filters["percent"] = _percent_filter

    @app.route("/")
    def dashboard():  # noqa: ANN202
        state = fetch()
        generated = _list_generated_artifacts()
        return render_template(
            "dashboard.html",
            state=state,
            refresh_seconds=refresh_seconds,
            actions=_serialize_catalogue(),
            current_run=_serialize_run(action_worker.current),
            last_run=_serialize_run(action_worker.last_completed),
            latest_generated=generated[0] if generated else None,
            recent_generated=generated[1:6] if len(generated) > 1 else [],
        )

    @app.route("/api/state")
    def api_state():  # noqa: ANN202
        return jsonify(_state_to_dict(fetch()))

    @app.route("/healthz")
    def healthz():  # noqa: ANN202
        # Cheap liveness — no DB hit. Useful for "is the dashboard
        # process up at all?" monitoring without load.
        return {"ok": True}

    @app.route("/api/actions")
    def api_actions():  # noqa: ANN202
        return jsonify({"actions": _serialize_catalogue()})

    @app.route("/api/actions/status")
    def api_actions_status():  # noqa: ANN202
        return jsonify({
            "current": _serialize_run(action_worker.current),
            "last": _serialize_run(action_worker.last_completed),
        })

    @app.route("/api/actions/<name>", methods=["POST"])
    def api_actions_start(name: str):  # noqa: ANN202
        spec = ACTIONS.get(name)
        if spec is None:
            return jsonify({
                "error": f"unknown action {name!r}",
                "available": sorted(ACTIONS.keys()),
            }), 404
        params = request.get_json(silent=True) or {}
        try:
            run = action_worker.start(spec, params)
        except ValueError as exc:
            return jsonify({"error": "invalid params", "detail": str(exc)}), 400
        except ActionWorker.BusyError as exc:
            # Include the currently-running action in the response so
            # the client can attach its SSE log without a second
            # round-trip. One call = busy status + live tail.
            return jsonify({
                "error": "busy",
                "detail": str(exc),
                "current_run": _serialize_run(action_worker.current),
            }), 409
        return jsonify({"started": _serialize_run(run)}), 202

    @app.route("/api/generated-maps")
    def api_generated_maps_list():  # noqa: ANN202
        items = _list_generated_artifacts()
        return jsonify({
            "latest": items[0] if items else None,
            "recent": items[:_GENERATED_LIST_CAP],
            "total_returned": len(items),
            "cap": _GENERATED_LIST_CAP,
        })

    @app.route("/api/generated-maps/<path:filename>")
    def api_generated_maps_download(filename: str):  # noqa: ANN202
        # Whitelist-only — the client can only fetch filenames the
        # generator itself produces. Anything else returns 404 so we
        # don't leak directory contents via probe behaviour.
        if not _SAFE_FILENAME_RE.match(filename):
            abort(404)
        if not _GENERATED_MAPS_DIR.exists():
            abort(404)
        return send_from_directory(
            str(_GENERATED_MAPS_DIR),
            filename,
            mimetype="application/json",
            as_attachment=False,
        )

    @app.route("/api/generated-maps/<path:filename>/emit-gbx", methods=["POST"])
    def api_emit_gbx(filename: str):  # noqa: ANN202
        # Resolve the JSON artifact, run the gbx_writer in-process
        # (typical wall-time ~300ms for a medium map — sync response is
        # friendlier than a full action-worker cycle for an operation
        # this cheap).
        if not _SAFE_FILENAME_RE.match(filename):
            abort(404)
        artifact_path = _GENERATED_MAPS_DIR / filename
        if not artifact_path.is_file():
            return jsonify({"error": "artifact not found"}), 404

        # Lazy imports keep Flask import cost low — the emit path is
        # the only place we need generation/gbx_writer + SubprocessParser.
        from src.generation.gbx_writer import (
            DEFAULT_GBX_OUTPUT_DIR,
            GbxEmitError,
            emit_gbx_from_artifact_file,
        )
        from src.parsers import SubprocessParser
        from src.storage.mariadb import open_connection
        from src.utils.config import load_config

        try:
            config = load_config(None)
        except Exception as exc:  # noqa: BLE001
            _LOG.exception("emit-gbx: config load failed")
            return jsonify({
                "error": "config load failed",
                "detail": f"{type(exc).__name__}: {exc}",
            }), 500
        gbx_cfg = (config.get("parsers") or {}).get("gbx") or {}
        executable = Path(
            gbx_cfg.get("executable")
            or "./parsers/gbx-wrapper/bin/Release/net8.0/GbxWrapper"
        )
        if not executable.is_absolute():
            executable = REPO_ROOT / executable
        if not executable.exists():
            return jsonify({
                "error": "wrapper binary missing",
                "detail": f"{executable}; run `dotnet build -c Release` "
                          f"on parsers/gbx-wrapper",
            }), 500
        parser = SubprocessParser(
            executable=executable,
            parser_version=str(gbx_cfg.get("parser_version", "0.1.0")),
            timeout_seconds=float(gbx_cfg.get("timeout_seconds", 30.0)),
        )
        try:
            conn = open_connection(config)
        except Exception as exc:  # noqa: BLE001
            _LOG.exception("emit-gbx: DB connect failed")
            return jsonify({
                "error": "db connect failed",
                "detail": f"{type(exc).__name__}: {exc}",
            }), 500
        try:
            try:
                result = emit_gbx_from_artifact_file(
                    conn,
                    artifact_path=artifact_path,
                    parser=parser,
                    output_dir=DEFAULT_GBX_OUTPUT_DIR,
                )
            except GbxEmitError as exc:
                _LOG.warning("emit-gbx failed: %s", exc)
                return jsonify({"error": "emit failed", "detail": str(exc)}), 500
        finally:
            conn.close()

        gbx_filename = result.output_path.name
        return jsonify({
            "artifact": filename,
            "gbx_filename": gbx_filename,
            "output_path": str(result.output_path),
            "new_map_uid": result.new_map_uid,
            "new_map_name": result.new_map_name,
            "block_count": result.block_count,
            "baked_block_count": result.baked_block_count,
            "duration_ms": result.subprocess_duration_ms,
            "stripped": result.stripped,
            "source_block_count": result.source_block_count,
            "removed_block_count": result.removed_block_count,
            "download_url": f"/api/generated-gbx/{gbx_filename}",
        }), 200

    @app.route("/api/generated-gbx/<path:filename>")
    def api_generated_gbx_download(filename: str):  # noqa: ANN202
        # Must match the `base{id}-{run_id}.Map.Gbx` filename convention
        # gbx_writer uses. as_attachment=True so browsers save to disk
        # rather than trying to render a binary.
        if not _SAFE_GBX_FILENAME_RE.match(filename):
            abort(404)
        if not _GENERATED_GBX_DIR.exists():
            abort(404)
        return send_from_directory(
            str(_GENERATED_GBX_DIR),
            filename,
            mimetype="application/octet-stream",
            as_attachment=True,
        )

    @app.route("/api/actions/<run_id>/log")
    def api_actions_log(run_id: str):  # noqa: ANN202
        run = _find_run(action_worker, run_id)
        if run is None:
            return jsonify({"error": f"unknown run id {run_id!r}"}), 404
        start_offset = int(request.args.get("offset", "0"))

        def _sse() -> Any:
            # Plain SSE framing: each stdout line → `data: ...\n\n`.
            # Closes when the action finishes or idle timeout fires.
            for line in tail_stream(run, start_offset=start_offset):
                # Split multi-line payloads across SSE messages so
                # receivers don't have to re-split.
                for sub in line.splitlines() or [""]:
                    yield f"data: {sub}\n\n"
            # Emit a terminal marker with the final status so the UI
            # can render "done" state without re-polling.
            final = _serialize_run(run) or {}
            yield (
                f"event: done\n"
                f"data: {final.get('status','unknown')}|{final.get('exit_code','?')}\n\n"
            )

        return Response(
            stream_with_context(_sse()),
            mimetype="text/event-stream",
            headers={"X-Accel-Buffering": "no", "Cache-Control": "no-cache"},
        )

    return app


def run() -> None:
    # Defaults bind to 0.0.0.0 so the dashboard is reachable from
    # other devices on the LAN (phone, second screen) without env
    # tweaking. The app surfaces pipeline telemetry only — no secrets,
    # no PII, no write endpoints — so LAN exposure is the intended
    # threat model for this dev tool. Set DASHBOARD_HOST=127.0.0.1 if
    # you want localhost-only.
    host = os.environ.get("DASHBOARD_HOST", "0.0.0.0")  # noqa: S104
    port = int(os.environ.get("DASHBOARD_PORT", "18080"))
    debug = os.environ.get("DASHBOARD_DEBUG", "").lower() in ("1", "true", "yes")
    app = create_app()
    _LOG.info("dashboard_web on http://%s:%d", host, port)
    app.run(host=host, port=port, debug=debug)
